### ISSUE TITLE
Design a Sponsors Display Page

### ISSUE THREAD

**Issue by VagishVela** [GDG-DevFest-Ohio/devfest-ohio-2023#40]
- **Description:** Create a sponsors page featuring Google, VTAKU, and Shrinkray. Emphasize VTAKU's Platinum sponsorship.
- **Acceptance Criteria:**
  1. Sponsors page is accessible from main navigation.
  2. Sponsor logos are displayed in varying sizes based on their tiers (Diamond, Platinum, Gold, Silver).
  3. VTAKU is prominently featured as a Platinum sponsor.

**Comment by shrinkray** [comment]
This is a stale request. It is anticipated that VTAKU will be a major sponsor, but since no sponsorship docs were finalized, and as far as I know, no institution or financial funds made available, this request cannot be acted upon. There is a sponsor page already. Once some sponsors are identified, logos provided, and a design to implement, then things can  be done.
